# Nixpacks configuration for GUIONIX
providers = ["node"]

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build:railway"
dependsOn = ["install"]

[start]
cmd = "npm start"
