# Nixpacks configuration for GUIONIX Next.js app - Force Nixpacks usage
providers = ["node"]

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NIXPACKS_BUILDER = "true"
DISABLE_DOCKER = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm ci --only=production --ignore-scripts"

[phases.build]
cmd = "npm run build:railway"
dependsOn = ["install"]

[start]
cmd = "npm start"

# Explicitly disable Docker detection
[build]
cmd = "echo 'Using Nixpacks, not Docker'"
