# Nixpacks configuration for GUIONIX - Simplified for Railway
providers = ["node"]

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm ci --omit=dev --ignore-scripts --no-audit --no-fund"

[phases.build]
cmd = "npm run build"
dependsOn = ["install"]

[start]
cmd = "npm start"
