# Nixpacks configuration for GUIONIX - Memory optimized for Railway
providers = ["node"]

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NODE_OPTIONS = "--max-old-space-size=2048 --optimize-for-size"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmd = "npm ci --production=false --maxsockets 1 --no-audit --no-fund"

[phases.build]
cmd = "npm run build:railway"
dependsOn = ["install"]

[start]
cmd = "npm start"
