[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "onFailure"

[env]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NODE_OPTIONS = "--max-old-space-size=4096"
