[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "onFailure"
numReplicas = 1

[env]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NIXPACKS_BUILDER = "true"
